//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCAT.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCAT.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blank Debug Display.
        /// </summary>
        internal static string LOCAT001CodeAction {
            get {
                return ResourceManager.GetString("LOCAT001CodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes with in model namespaces should have a DebugDisplay..
        /// </summary>
        internal static string LOCAT001Description {
            get {
                return ResourceManager.GetString("LOCAT001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should have a DebugDisplay..
        /// </summary>
        internal static string LOCAT001MessageFormat {
            get {
                return ResourceManager.GetString("LOCAT001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Debug Display, should include data from members..
        /// </summary>
        internal static string LOCAT001Title {
            get {
                return ResourceManager.GetString("LOCAT001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Displays Should not be empty..
        /// </summary>
        internal static string LOCAT002MessageFormat {
            get {
                return ResourceManager.GetString("LOCAT002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Display value is empty..
        /// </summary>
        internal static string LOCAT002Title {
            get {
                return ResourceManager.GetString("LOCAT002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Displays Should contain member data..
        /// </summary>
        internal static string LOCAT003MessageFormat {
            get {
                return ResourceManager.GetString("LOCAT003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Display value should not be constant..
        /// </summary>
        internal static string LOCAT003Title {
            get {
                return ResourceManager.GetString("LOCAT003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using &apos;{0} {2}&apos; instead of &apos;{1} {2}&apos;..
        /// </summary>
        internal static string LOCAT004MessageFormat {
            get {
                return ResourceManager.GetString("LOCAT004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;is&apos; pattern for constant checks..
        /// </summary>
        internal static string LOCAT004Title {
            get {
                return ResourceManager.GetString("LOCAT004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async Method names should end with Async..
        /// </summary>
        internal static string LOCAT005Title {
            get {
                return ResourceManager.GetString("LOCAT005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment contains `{0}`. Address or create issue: `{1}`.
        /// </summary>
        internal static string LOCAT006MessageFormat {
            get {
                return ResourceManager.GetString("LOCAT006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO Comments should be fixed, or be added as issues on the projects repo..
        /// </summary>
        internal static string LOCAT006Title {
            get {
                return ResourceManager.GetString("LOCAT006Title", resourceCulture);
            }
        }
    }
}
